In [1]:
import numpy as np

In [2]:
data1 = [10, 9.9, 9, 11, 8] 

In [3]:
data1

[10, 9.9, 9, 11, 8]

In [4]:
type(data1) 

list

In [6]:
arr1 = np.array(data1) 

In [7]:
np.array?

In [8]:
arr1

array([ 10. ,   9.9,   9. ,  11. ,   8. ])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.dtype

dtype('float64')

In [11]:
np.zeros((3,5)) 

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones(7) 

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
np.ones((2,7)) 

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [14]:
data2 = [ [1,2,3,4,5],[6,7,8,9,10] ] 

In [15]:
arr2 = np.array(data2) 

In [16]:
arr2.dtype

dtype('int32')

In [17]:
arr = np.array([1,2,3,4,5] , dtype=np.int64)

In [18]:
arr.dtype

dtype('int64')

In [19]:
float_arr = arr.astype(np.float64) 

In [20]:
float_arr.dtype

dtype('float64')

In [21]:
arr1 = np.array( [ [1,2,3],[4,5,6] ], dtype=np.float64) 

In [22]:
arr2 = np.array( [ [7,8,9,],[10,11,12] ], dtype=np.float64) 

In [23]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [24]:
arr2

array([[  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [25]:
arr1 + arr2

array([[  8.,  10.,  12.],
       [ 14.,  16.,  18.]])

In [26]:
arr1 * arr2

array([[  7.,  16.,  27.],
       [ 40.,  55.,  72.]])

In [27]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [28]:
arr1 * 2

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [29]:
arr1 ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [30]:
names = np.array(['pyo', 'sunyoung','psy', 'pyo', 'sunyoung','sunny','sunyoung'])
data = np.random.randn(7,4) 

In [31]:
names

array(['pyo', 'sunyoung', 'psy', 'pyo', 'sunyoung', 'sunny', 'sunyoung'],
      dtype='<U8')

In [32]:
data

array([[-0.7709964 ,  0.31305644, -0.83039417, -0.88197982],
       [ 1.07276959,  0.75413338, -0.74379446,  0.41261684],
       [ 1.41368451,  1.15074991, -0.57576506, -1.50612664],
       [-0.6939472 ,  0.13945345,  0.86615071, -0.05435675],
       [-1.21606019, -0.86374928,  0.50698867,  0.62902697],
       [ 0.44091796,  0.6217672 , -1.72116468, -0.3882266 ],
       [-0.57187969,  0.8820428 ,  0.41669524, -1.11184805]])

In [33]:
names == 'sunyoung' 

array([False,  True, False, False,  True, False,  True], dtype=bool)

In [34]:
data[ names == 'sunyoung' ,  : ]  

array([[ 1.07276959,  0.75413338, -0.74379446,  0.41261684],
       [-1.21606019, -0.86374928,  0.50698867,  0.62902697],
       [-0.57187969,  0.8820428 ,  0.41669524, -1.11184805]])

In [35]:
data[ (names == 'sunyoung') | (names == 'pyo') ]  

array([[-0.7709964 ,  0.31305644, -0.83039417, -0.88197982],
       [ 1.07276959,  0.75413338, -0.74379446,  0.41261684],
       [-0.6939472 ,  0.13945345,  0.86615071, -0.05435675],
       [-1.21606019, -0.86374928,  0.50698867,  0.62902697],
       [-0.57187969,  0.8820428 ,  0.41669524, -1.11184805]])

In [36]:
data[ : , 3]

array([-0.88197982,  0.41261684, -1.50612664, -0.05435675,  0.62902697,
       -0.3882266 , -1.11184805])

In [37]:
data[ : , 3] < 0

array([ True, False,  True,  True, False,  True,  True], dtype=bool)

In [38]:
data[data[ : , 3] < 0 , : ] = 0

In [39]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.07276959,  0.75413338, -0.74379446,  0.41261684],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.21606019, -0.86374928,  0.50698867,  0.62902697],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [40]:
a = [1,2,3] 
b = [1,2,3]
print(a+b) 

[1, 2, 3, 1, 2, 3]


In [42]:
c = np.array([1,2,3]) 
d = np.array([1,2,3]) 
print(c+d) 

[2 4 6]


In [43]:
c * 2

array([2, 4, 6])

In [44]:
c = np.array([1,2,3]) 
d = np.array([1,2,3,4])  
print(c+d) 

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [45]:
c = np.array([1,2,3,4]) 
d = np.array([1,2,3,4])  
print(sum(c*d))  

30
