In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10) 

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr) 

numpy.ndarray

In [5]:
np.sqrt?

In [6]:
np.sqrt(arr) 

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [8]:
np.exp?

In [9]:
np.exp(arr) 

array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03])

In [10]:
x = np.random.rand(10)
y = np.random.rand(10) 

In [11]:
x

array([ 0.99007883,  0.30632879,  0.06784334,  0.1814477 ,  0.21651972,
        0.04513575,  0.92254385,  0.5571994 ,  0.90930436,  0.96017864])

In [12]:
y

array([ 0.46461415,  0.90113238,  0.38217745,  0.10844167,  0.19459367,
        0.58985281,  0.92401377,  0.13848974,  0.35871051,  0.35101816])

In [13]:
np.maximum?

In [14]:
np.maximum(x,y) 

array([ 0.99007883,  0.90113238,  0.38217745,  0.1814477 ,  0.21651972,
        0.58985281,  0.92401377,  0.5571994 ,  0.90930436,  0.96017864])

In [15]:
arr2 = np.random.randn(6,5) 

In [16]:
arr2

array([[ 0.34325088,  1.02812059, -0.03957931,  0.42608428,  0.97891825],
       [-0.60249633, -0.35642644,  1.27085981,  0.50303885, -0.81883238],
       [ 1.16358824,  0.8169074 ,  0.27023184,  0.01148566,  0.5753777 ],
       [ 2.02485152, -0.876119  ,  0.74983683, -0.9830517 ,  0.26384713],
       [ 0.002678  ,  1.07424046,  0.25743658,  1.04098415,  0.29562699],
       [-0.58675459,  0.2585481 ,  0.13472673,  0.79917769, -0.84333857]])

In [17]:
arr2.sum() 

9.1832193771755346

In [19]:
arr2.sum(axis=0) 

array([ 2.34511771,  1.94527111,  2.64351248,  1.79771894,  0.45159913])

In [20]:
arr2.mean(axis=1) 

array([ 0.54735894, -0.0007713 ,  0.56751817,  0.23587296,  0.53419324,
       -0.04752813])

In [21]:
arr2.sum(axis=1) 

array([ 2.73679468, -0.00385649,  2.83759084,  1.17936479,  2.67096619,
       -0.23764063])

In [22]:
arr2 > 0

array([[ True,  True, False,  True,  True],
       [False, False,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True, False]], dtype=bool)

In [23]:
(arr2 > 0).sum() 

22

In [24]:
arr3 = np.random.randn(7) 
arr3

array([ 0.5343254 , -0.82399908,  1.01193663,  0.22425379,  1.13809535,
       -0.10581182,  0.1659438 ])

In [25]:
arr3.sort() 

In [26]:
arr3

array([-0.82399908, -0.10581182,  0.1659438 ,  0.22425379,  0.5343254 ,
        1.01193663,  1.13809535])

In [27]:
arr3.sort?

In [28]:
np.sort?

In [29]:
np.sort(arr)[::-1] 

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [30]:
arr4 = np.random.randn(5,3) 
arr4

array([[ 1.44867401,  0.14290742,  0.62669327],
       [-0.61399914,  0.91351882, -0.01932809],
       [ 0.17296243, -0.75988848,  0.44091468],
       [-0.49618821,  0.17330431, -0.79123114],
       [ 0.12445479, -2.0337316 , -1.1029504 ]])

In [31]:
type(arr4) 

numpy.ndarray

In [32]:
np.sort(arr4, axis=0) 

array([[-0.61399914, -2.0337316 , -1.1029504 ],
       [-0.49618821, -0.75988848, -0.79123114],
       [ 0.12445479,  0.14290742, -0.01932809],
       [ 0.17296243,  0.17330431,  0.44091468],
       [ 1.44867401,  0.91351882,  0.62669327]])

In [33]:
np.sort(arr4, axis=1) 

array([[ 0.14290742,  0.62669327,  1.44867401],
       [-0.61399914, -0.01932809,  0.91351882],
       [-0.75988848,  0.17296243,  0.44091468],
       [-0.79123114, -0.49618821,  0.17330431],
       [-2.0337316 , -1.1029504 ,  0.12445479]])

In [34]:
arr4.sort(axis=1)

In [35]:
arr4

array([[ 0.14290742,  0.62669327,  1.44867401],
       [-0.61399914, -0.01932809,  0.91351882],
       [-0.75988848,  0.17296243,  0.44091468],
       [-0.79123114, -0.49618821,  0.17330431],
       [-2.0337316 , -1.1029504 ,  0.12445479]])

In [36]:
names = np.array(['pyo', 'sunyoung','psy', 'pyo', 'sunyoung','sunny','sunyoung']) 

In [37]:
np.unique(names) 

array(['psy', 'pyo', 'sunny', 'sunyoung'],
      dtype='<U8')