In [1]:
import numpy as np

In [2]:
data1 = [10, 9.9, 9, 11, 100, 34.3, 1, -10.3]

In [3]:
data1

[10, 9.9, 9, 11, 100, 34.3, 1, -10.3]

In [4]:
type(data1)

list

In [ ]:
arr = np.array(data1)

In [19]:
arr.dtype

dtype('float64')

In [5]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.ones((2, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [8]:
data2 = [[1,2,3,4,5], [6,7,8,9,10]]

In [14]:
arr2 = np.array(data2)

In [15]:
arr2.dtype

dtype('int64')

In [17]:
arr2.dtype

dtype('int64')

In [20]:
float_arr = arr.astype(np.float64)

In [21]:
float_arr.dtype

dtype('float64')

In [24]:
arr1 = np.array([[1,2,3], [4,5,6]], dtype=np.float64)
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
arr2 = np.array([[7,8,9], [10,11,12]], dtype=np.float64)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [26]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [27]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [28]:
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [29]:
names = np.array(['aaa', 'bbb', 'ccc', 'ddd', 'eee'])
data = np.random.randn(7, 4)

In [30]:
names

array(['aaa', 'bbb', 'ccc', 'ddd', 'eee'], dtype='<U3')

In [31]:
data

array([[ 0.79420866,  0.80251941, -0.53452314,  0.55283626],
       [-0.5891281 ,  0.59916207, -0.70502275,  1.26087494],
       [-0.47339373,  0.53321482, -0.70103283,  0.77890627],
       [ 0.41947686,  0.920728  , -1.1840911 , -0.20537597],
       [-1.36830935, -0.78435889,  0.16192066,  0.38886887],
       [-0.98898236, -0.75240234,  0.51331178, -0.230988  ],
       [ 0.2209811 , -0.08756   , -1.55240593,  0.17898193]])

In [32]:
names == 'bbb'

array([False,  True, False, False, False])

In [36]:
data[:, 3]

array([ 0.55283626,  1.26087494,  0.77890627, -0.20537597,  0.38886887,
       -0.230988  ,  0.17898193])

In [37]:
data[:, 3] < 0

array([False, False, False,  True, False,  True, False])

In [42]:
data[data[:, 3] < 0, :] = 0
data

array([[ 0.79420866,  0.80251941, -0.53452314,  0.55283626],
       [-0.5891281 ,  0.59916207, -0.70502275,  1.26087494],
       [-0.47339373,  0.53321482, -0.70103283,  0.77890627],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.36830935, -0.78435889,  0.16192066,  0.38886887],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.2209811 , -0.08756   , -1.55240593,  0.17898193]])

In [43]:
a = [1,2,3]
b = [1,2,3]
print(a+b)

[1, 2, 3, 1, 2, 3]


In [48]:
c = np.array([1,2,3])
d = np.array([1,2,3])
print(c+d)

[2 4 6]


In [49]:
c * 2

array([2, 4, 6])