In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.sqrt?

In [6]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.exp?

In [8]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [9]:
x = np.random.rand(10)
y = np.random.rand(10)

In [11]:
print(x)
print(y)

[0.56340451 0.42045511 0.04876852 0.6333329  0.10091122 0.67413291
 0.71132405 0.73567041 0.86000782 0.58218521]
[0.99525896 0.4077845  0.8973333  0.67865336 0.37052128 0.9093007
 0.276957   0.5371079  0.01064449 0.21534083]


In [13]:
np.maximum?

In [14]:
np.maximum(x, y)

array([0.99525896, 0.42045511, 0.8973333 , 0.67865336, 0.37052128,
       0.9093007 , 0.71132405, 0.73567041, 0.86000782, 0.58218521])

In [18]:
arr2 = np.rarange.randn(10, 5)

AttributeError: module 'numpy' has no attribute 'rarange'

In [19]:
arr.mean()

5.0

In [20]:
(arr > 0).sum()

9

In [23]:
arr3 = np.random.randn(7)
arr3

array([ 0.30718075,  1.50623487, -0.14688041, -2.91146585, -0.73134413,
       -0.51019663,  0.68605401])

In [26]:
arr3.sort()
arr3

array([-2.91146585, -0.73134413, -0.51019663, -0.14688041,  0.30718075,
        0.68605401,  1.50623487])

In [28]:
np.sort?

In [29]:
np.sort(arr3)[::-1]

array([ 1.50623487,  0.68605401,  0.30718075, -0.14688041, -0.51019663,
       -0.73134413, -2.91146585])

In [30]:
type(arr3)

numpy.ndarray

In [31]:
np.sort(arr3, axis=0)

array([-2.91146585, -0.73134413, -0.51019663, -0.14688041,  0.30718075,
        0.68605401,  1.50623487])

In [32]:
np.sort(arr3, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [35]:
names = np.array(['aa','bb','cc','dd','ee','a','aa','cc','abc'])

In [36]:
np.unique(names)

array(['a', 'aa', 'abc', 'bb', 'cc', 'dd', 'ee'], dtype='<U3')